name: "Workflow"
on:
  push:
    branches: [ master ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, ubuntu-latest ]
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Setup CMake"
        uses: lukka/get-cmake@latest

      - name: "Run CMake"
        run: cmake --preset ninja -B build

      - name: "Build"
        run: cmake --build build
