name: "Workflow"
on:
  push:
    branches: [ master ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, ubuntu-latest ]
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Setup (Windows)"
        if: ${{ matrix.os == 'windows-latest' }}
        uses: ilammy/msvc-dev-cmd@v1

      - name: "Setup (Linux)"
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: egor-tensin/setup-clang@v1

      - name: "Setup CMake"
        uses: lukka/get-cmake@latest

      - name: "Run CMake (Windows)"
        if: ${{ matrix.os == 'windows-latest' }}
        run: cmake --preset release-windows

      - name: "Build (Windows)"
        if: ${{ matrix.os == 'windows-latest' }}
        run: cmake --build build/release-windows

      - name: "Run CMake (Linux)"
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: cmake --preset release-linux

      - name: "Build (Linux)"
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: cmake --build build/release-linux
